---
title: "Homework 1"
author: Nancy Fang (nf2466)
output: github_document
---
This is my solution to HW1

```{r}
library(tidyverse)
```
## Problem 1

```{r}
prob1_df =
  tibble (
    samp = rnorm(10),
    samp_gt_0 = samp > 0,
    char_vec = c( "a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    factor_vec = factor (c("low", "low", "low", "mod", "mod", "mod", "mod", "high", "high", "high"))
)

```
Take the mean of each variable in my data frame
```{r mean_pull_var}
mean (pull(prob1_df, samp))
mean (pull(prob1_df, samp_gt_0))
mean (pull(prob1_df, char_vec))
mean (pull(prob1_df, factor_vec))
```
I can take the mean of numbers and logical but not character or factor variables

```{r eval=FALSE}
as.numeric (pull(prob1_df, samp))
as.numeric (pull(prob1_df, samp_gt_0))
as.numeric (pull(prob1_df, char_vec))
as.numeric (pull(prob1_df, factor_vec))
```
You can convert a factor vector to numeric, but not character vectors to numeric.

```{r}
as.numeric (pull(prob1_df, samp_gt_0))*pull(prob1_df, samp) #convert the logical vector to numeric, and multiply the random sample by the result

as.factor(pull(prob1_df, samp_gt_0))*pull(prob1_df, samp) #convert the logical vector to a factor, and multiply the random sample by the result

prob1_factor = 
  as.factor(pull(prob1_df, samp_gt_0)) #convert the logical vector to a factor and naming is prob1_factor

as.numeric (prob1_factor)*pull(prob1_df, samp) # convert the result to numeric, and multiply the random sample by the result
```
# Problem 2
```{r}
data("penguins", package = "palmerpenguins")
view(penguins)#data variables in the this dataset show there are 3 species of penguins from 3 islands and include variables of bill length, depth, flipper length, body mass, sex, and year.
nrow(penguins) #there are 344 individual inputs (rows)
ncol(penguins) #there are 8 different variables (columns)

#take subset of flipper length > 0 and assign name 'num_flipper'
num_flipper=
  subset(penguins,flipper_length_mm>0,) 
#change 'num_flipper' to numeric
    as.numeric(pull(num_flipper,flipper_length_mm)) 
#take mean of numerical values of flipper length  
     mean(as.numeric(pull(num_flipper,flipper_length_mm)))

#plot of bill length vs flipper length
bill_flipper_plot=
  ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm)) + geom_point(aes(color=species))

#save ggplot
ggsave("bill_flipper_plot.pdf", bill_flipper_plot, width=8, height=5)
```

